Nifty 50 Analysis
abhisheks008/ML-Crate pull request #340
Opened 2022-07-30 09:02 UTC by Avik-creator

# Pull Request for ML-Crate 💡

## Issue Title : Nifty 50 Analysis

- **Info about the related issue (Aim of the project)** : Analyze the NIFTY Indices of the stock market for the time period of Jan 22.
- **Name:** Avik Mukherjee
- **GitHub ID:** Avik-creator
- **Idenitfy yourself:** HSoC participant.

Closes: #182 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-07-30 09:02 UTC, Avik-creator commented
@abhisheks008 Please check and review it.

2022-07-31 03:47 UTC, abhisheks008 requested changes
1. Remove the `Model/DATASET` folder, you have uploaded the csv files in the Dataset folder, no need to add them again.
2. In your notebook, the figures are not visible, while you running the code `fig.show()`

2022-07-31 16:20 UTC, Avik-creator commented
@abhisheks008 Please check and review.

2022-07-31 16:32 UTC, abhisheks008 approved these changes

2022-07-31 16:33 UTC, merged