Stock news sentiment analysis
abhisheks008/ML-Crate pull request #454
Opened 2023-12-19 12:22 UTC by Shobhit-Bandhu

# Pull Request for ML-Crate 💡

## Issue Title: Stock News Sentiment Analysis #351

- **Info about the related issue (Aim of the project)** : 
- **Name:** Shobhit-Bandhu
- **GitHub ID:** Shobhit-Bandhu
- **Idenitfy yourself:** Contributor KWOC '23

Closes: #351

### Describe the add-ons or changes you've made 📃

Preprocessed data, added SVM model.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

2023-12-19 13:34 UTC, abhisheks008 commented
Please complete the whole project and update the blanks in the Jupyter Notebook and `README.md`. Once you are done with this, do let me know.

2023-12-22 04:06 UTC, abhisheks008 requested changes
Also check out the errors of Tensorflow modelling and try impose it properly.

2023-12-22 04:06 UTC, abhisheks008 commented on Stock News Sentiment Analysis/Model/README.md
> +# Stock News Sentiment Analysis
Please follow the `README.md` template and update it accordingly. Here is the template, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md

2023-12-23 03:45 UTC, abhisheks008 commented
Hi @Shobhit-Bandhu I have seen that CNNs are not properly implemented in your project, you can remove it from the notebook.

2023-12-24 05:09 UTC, abhisheks008 commented
Hey @Shobhit-Bandhu your implemented models are not even having accuracy score of 80 atleast. Please upgrade the models and try to achieve an accuracy of atleast 80%.

2023-12-25 13:05 UTC, Shobhit-Bandhu commented
@abhisheks008 Any suggestions? Should I use BERT models?

2023-12-26 05:05 UTC, abhisheks008 commented
> @abhisheks008 Any suggestions? Should I use BERT models?

Yeah you can try that.

2023-12-29 12:30 UTC, Shobhit-Bandhu commented
@abhisheks008 I can't seem to do better than 54%...

2024-01-01 06:18 UTC, abhisheks008 commented
Hi @Shobhit-Bandhu sorry for the delay, as I was in vacation. Can you please update the `README.md` file with the newly added model's accuracy score.

2024-01-01 19:28 UTC, Shobhit-Bandhu commented
@abhisheks008 Anything else you would like added?

2024-01-02 06:05 UTC, abhisheks008 approved these changes
LGTM! Your PR is approved and ready to be merged.
@Shobhit-Bandhu

2024-01-02 06:05 UTC, merged