Years of experience and Salary dataset
abhisheks008/ML-Crate pull request #62
Opened 2021-12-30 07:23 UTC by BhaswatiRoy

## Issue Title :

- Info about the related issue (Aim of the project)

- [x] SWOC Participant 
- [x] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2021-12-30 07:43 UTC, abhisheks008 requested changes
Do the needful changes @BhaswatiRoy

2021-12-30 07:43 UTC, abhisheks008 commented on Years of experience and Salary dataset/Model/README.md
> +
Follow the README.md template and insert proper description of the project. Follow this for reference, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md

2021-12-30 07:43 UTC, abhisheks008 commented on Years of experience and Salary dataset/README.md
> +
Delete this file.

2021-12-30 14:07 UTC, abhisheks008 requested changes
Delete the Model/README.md file @BhaswatiRoy

2021-12-31 05:00 UTC, BhaswatiRoy commented
I've done the required changes.
Do let me know if anything else is needed!

2021-12-31 13:22 UTC, abhisheks008 approved these changes

2021-12-31 13:23 UTC, abhisheks008 commented
Good work keep it up @BhaswatiRoy

2021-12-31 13:23 UTC, merged

2021-12-31 13:53 UTC, BhaswatiRoy commented
> Good work keep it up @BhaswatiRoy

Thank you