Pcos Detection
abhisheks008/ML-Crate pull request #635
Opened 2024-06-06 15:20 UTC by payalsinha12

# Pull Request for ML-Crate 💡

## Issue Title: [PROJECT ADDITION]- PCOS DETECTION 

- **Info about the related issue (Pcos Detection )** : helps to detect that the person is suffering from Pcos or not.
- **Name:** Payal SInha
- **GitHub ID:** https://github.com/payalsinha12
- **Idenitfy yourself:** A Web Developer and Graphic Designer

Closes: #624 

### Describe the add-ons or changes you've made 📃

I made a project on Pcos Detection using the dataset taken from Kaggle.

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-06-06 17:11 UTC, abhisheks008 requested changes
Follow the project structure and update your files accordingly.
@payalsinha12

2024-06-06 17:26 UTC, abhisheks008 commented
https://github.com/abhisheks008/ML-Crate/tree/main/ASELSAN%20Stock%20Prices

Follow the project structure and put your files.

2024-06-06 19:11 UTC, payalsinha12 reviewed
changes done.

2024-06-07 03:45 UTC, abhisheks008 requested changes
1. Remove the `Pcos Detection.ipynb` file, which is outside the project folder.
2. File names should be as `README.md`, `requirements.txt`.
3. Update the README file as per the given template, https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md. Make it eye pleasing as it's shown in the template, using different emojis.
4. Remove the `.csv` file from the Model folder. as you have already shared the dataset file inside the Dataset folder.
5. Upload the EDA results inside the Images folder including the confusion matrices, accuracy graphs.
6. Add different visualization images inside the README file and showcase different aspects of the dataset.

@payalsinha12

2024-06-07 07:01 UTC, payalsinha12 reviewed
changes done

2024-06-07 09:16 UTC, abhisheks008 requested changes
1. Remove the images from the Model folder and put them inside the Images folder.
2. Remove the `desktop.ini` file.

2024-06-07 10:54 UTC, payalsinha12 commented
you told me to add different visualization images inside the README file. the images present inside the model folder is actually present in the README file now you are asking to delete the pictures what should i do ?? and i removed the desktop.ini file @abhisheks008

2024-06-07 10:54 UTC, payalsinha12 reviewed
done

2024-06-07 17:35 UTC, abhisheks008 commented
> you told me to add different visualization images inside the README file. the images present inside the model folder is actually present in the README file now you are asking to delete the pictures what should i do ?? and i removed the desktop.ini file @abhisheks008

If you remove the images from the Model folder and put them inside the Images folder, you can still hyperlink the images and use them inside the README irrespective of the folder.

2024-06-07 18:18 UTC, payalsinha12 reviewed
Hyperlink added @abhisheks008

2024-06-09 16:41 UTC, payalsinha12 commented
@abhisheks008 hey please review this

2024-06-11 05:57 UTC, abhisheks008 commented
<img width="772" alt="image" src="https://github.com/abhisheks008/ML-Crate/assets/68724349/3e94be1d-7f65-403f-a4a5-fc3cd5929c6c">

You haven't fixed this.

2024-06-11 11:34 UTC, abhisheks008 commented
> <img alt="image" width="772" src="https://private-user-images.githubusercontent.com/68724349/338454140-3e94be1d-7f65-403f-a4a5-fc3cd5929c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDU5MTIsIm5iZiI6MTcxODEwNTYxMiwicGF0aCI6Ii82ODcyNDM0OS8zMzg0NTQxNDAtM2U5NGJlMWQtN2Y2NS00MDNmLWE0YTUtZmMzY2Q1OTI5YzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDExMzMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NjZkMTk5M2I2Y2JhOGYyZGVkY2EyNjUyMmE1NDliYjcyMjIyYjkyOTM0MTM2OTIxMTE5ZDlhYTc2YjljMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0rIa7q9M9ZLe6tAdVscHlUUK5smEuWKACGHpTPGl1NA">
> You haven't fixed this.

Create a table for showing the accuracy scores, it's not feasible to show the accuracy scores like this. It's a minor markdown change you need to do.

2024-06-13 13:32 UTC, payalsinha12 commented
please tell in which folder i have to create the table suggest the proper path for it @abhisheks008

2024-06-15 06:47 UTC, abhisheks008 requested changes

2024-06-15 06:47 UTC, abhisheks008 commented on Pcos Detection/Model/README.md
> +📈 **Performance of the Models based on the Accuracy Scores**
The markdown script you have written is not creating a table, instead it is showing one after another.

This is what you need to fix.

2024-06-15 09:37 UTC, payalsinha12 reviewed
Check now @abhisheks008

2024-06-15 17:24 UTC, payalsinha12 commented
@abhisheks008 please review it and merge it

2024-06-15 17:39 UTC, abhisheks008 commented
![image](https://github.com/abhisheks008/ML-Crate/assets/68724349/8cd6c683-5501-4d22-9626-86f9dbc1dee0)

Images are not visible.

2024-06-15 18:23 UTC, payalsinha12 reviewed
all the changes are done successfully . I've uploaded the drive link and it is working now @abhisheks008

2024-06-15 18:23 UTC, payalsinha12 commented
please review it asap @abhisheks008

2024-06-16 03:31 UTC, abhisheks008 commented
No need to add drive link. You can just hyperlink the images from the Images folder to the README.

2024-06-16 07:54 UTC, payalsinha12 commented
but what is the need of changing again if that link is working ultimately we want to see the pictures and it is visible then why i have to change it . please assign me as those links are also working now

2024-06-17 20:58 UTC, payalsinha12 reviewed
i have done the changes now please review it and merge it @abhisheks008

2024-06-19 05:05 UTC, abhisheks008 approved these changes
Approved @payalsinha12

2024-06-19 05:06 UTC, merged

2024-07-21 14:02 UTC, abhisheks008 commented
Hi @payalsinha12 sorry for the inconvenience caused from my end. Please share your email address for further communications. 

I have added your points in the excel sheet, no worries now.

2024-07-21 14:27 UTC, payalsinha12 commented
> Hi @payalsinha12 sorry for the inconvenience caused from my end. Please share your email address for further communications.
> 
> I have added your points in the excel sheet, no worries now.

sinhapayal2913@gmail.com 
Thank you for the help