House-Price-Prediction
abhisheks008/ML-Crate pull request #82
Opened 2022-01-12 13:21 UTC by Vanshikagoel0012

## Issue Title :

- Info about the related issue (Aim of the project)

- [ ] SWOC Participant 
- [ ] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-01-12 15:12 UTC, abhisheks008 requested changes
1. Delete the unnecessary files that you have attached in the main branch.
2. Follow the proper structure of the README.md file.
3. Use 4-5 models and make a comparison to achieve the best fitted model.
4. For reference you can take a look at the others' projects.

2022-01-12 19:27 UTC, Vanshikagoel0012 commented
Sir, I have  followed the proper process of it and also readme is attached and extra file are not visible to time kindly point out that

2022-01-13 07:08 UTC, abhisheks008 requested changes

2022-01-13 07:08 UTC, abhisheks008 commented on readme.txt
> +# Linear-Regression-Model-for-House-Price-Prediction.
delete these kind of files which are attached directly in main repo not in your project folder

2022-01-13 07:09 UTC, abhisheks008 commented
And you have not followed the format of README.md file. Please follow the proper format. Use more algorithms (4-5) and justify the best fitted model.

2022-01-13 07:10 UTC, abhisheks008 commented
https://github.com/abhisheks008/ML-Crate/blob/main/.github/readme_template.md
Follow this.

2022-01-14 15:31 UTC, closed without merging