Stress Detection
abhisheks008/ML-Crate pull request #97
Opened 2022-01-24 07:10 UTC by BhaswatiRoy

## Issue Title :

- Info about the related issue (Aim of the project)

- [ ] SWOC Participant 
- [ ] Contributor

Closes: #issue number that will be closed through this PR

### Describe the add-ons or changes you've made

Give a clear description of what have you added or modifications made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-01-24 07:20 UTC, abhisheks008 requested changes
1. Provide the URL of the dataset in the `Dataset/README.md` file.
2. Upload some visualization images in the `Images` folder.
3. Remove the `README.md` file in the `Images` folder.
4. Remove the `README.md` file in the `Model` folder.

@BhaswatiRoy

2022-01-26 13:16 UTC, abhisheks008 commented
@BhaswatiRoy do the needful changes, so that I can proceed further with your PR.

2022-01-26 14:04 UTC, BhaswatiRoy commented
Yah I will finish it soon
Actually my exams are on so a bit delay occurred!

2022-02-01 06:15 UTC, abhisheks008 approved these changes

2022-02-01 06:15 UTC, merged